apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: reporting-func
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: gcr.io/integral-bliss-306817/reporting-func:v2
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      serviceAccountName: reporting-func