apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trigger-func
  name: trigger-func
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger-func
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trigger-func
    spec:
      volumes:
      - name: google-cloud-key
        secret:
          secretName: pubsub-key
      containers:
      - image: gcr.io/integral-bliss-306817/trigger-func:latest
        name: trigger-func
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: google-cloud-key
          mountPath: /var/secrets/google
        env:
          - name: PORT
            value: "3000"
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: trigger-func-svc
  name: trigger-func-svc
spec:
  ports:
  - name: http
    port: 3000
  selector:
    app: trigger-func
  type: NodePort
status:
  loadBalancer: {}