apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: analysis-func
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: {{IMAGE}}
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
      serviceAccountName: analysis-func